# Generated by Django 6.0.6 on 2026-08-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
